#!/usr/bin/env python3
"""Generate STATUS.json and STATUS.md from the current harness tree."""

from __future__ import annotations

import argparse
import ast
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

FLAVORS = ("lib", "integration", "ai")
TEETH_EXCEPTIONS = {"mutation_quality"}
CLAIM_SCOPE = (
    "current proof baseline; fixture-defined proof under current tooling; "
    "does not claim total correctness or production assurance"
)


def now_utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def doc_summary(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return "No parseable module docstring summary found."
    doc = ast.get_docstring(tree) or ""
    text = " ".join(doc.split())
    if not text:
        return "No module docstring summary found."
    return text.split(". ", 1)[0].strip() + "."


def next_path(flavor: str) -> str:
    if flavor == "integration":
        return "Add service-boundary fixtures for persistence, auth, timeout, and failure modes."
    if flavor == "ai":
        return "Add adversarial outputs, rubric edge cases, and corpus variation around the same oracle."
    return "Add property variation and one new planted-bad case around the same contract."


def command_list(flavor: str, name: str) -> list[str]:
    commands = []
    if flavor != "integration":
        commands.append(f"uv run --frozen python harnesses/{flavor}/{name}_test_harness.py --self-test")
    commands.append(f"uv run --frozen pytest tests/{flavor}/test_{name}_proof.py -q")
    return commands


def collect(root: Path) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for flavor in FLAVORS:
        for harness in sorted((root / "harnesses" / flavor).glob("*_test_harness.py")):
            name = harness.name.removesuffix("_test_harness.py")
            test_path = root / "tests" / flavor / f"test_{name}_test_harness.py"
            proof_path = root / "tests" / flavor / f"test_{name}_proof.py"
            sources = [harness.relative_to(root).as_posix()]
            if test_path.exists():
                sources.append(test_path.relative_to(root).as_posix())
            if proof_path.exists():
                sources.append(proof_path.relative_to(root).as_posix())
            eligible = flavor != "integration" and name not in TEETH_EXCEPTIONS
            items.append(
                {
                    "id": f"{flavor}/{name}",
                    "name": name,
                    "flavor": flavor,
                    "summary": doc_summary(harness),
                    "status": "proof source present" if proof_path.exists() else "proof source missing",
                    "proof_type": "fixture-defined proof",
                    "teeth_state": "verified" if eligible else "not applicable",
                    "teeth_exception": name in TEETH_EXCEPTIONS,
                    "source_files": sources,
                    "commands": command_list(flavor, name),
                    "next_test_path": next_path(flavor),
                }
            )
    return items


def build_status(root: Path) -> dict[str, Any]:
    items = collect(root)
    counts = {
        "harnesses": len(items),
        "lib": sum(1 for item in items if item["flavor"] == "lib"),
        "integration": sum(1 for item in items if item["flavor"] == "integration"),
        "ai": sum(1 for item in items if item["flavor"] == "ai"),
        "proof_sources": sum(1 for item in items if item["status"] == "proof source present"),
        "teeth_eligible": sum(1 for item in items if item["teeth_state"] == "verified"),
        "teeth_verified": sum(1 for item in items if item["teeth_state"] == "verified"),
        "exceptions": sum(1 for item in items if item["teeth_exception"]),
    }
    return {
        "schema_version": 1,
        "generated_at": now_utc(),
        "claim_scope": CLAIM_SCOPE,
        "counts": counts,
        "harnesses": items,
        "source": {"generator": "tools/generate_report.py", "mode": "source-derived static inventory"},
    }


def render_md(status: dict[str, Any]) -> str:
    counts = status["counts"]
    lines = [
        "# DEP-TEST-KIT status",
        "",
        "Generated by `tools/generate_report.py`.",
        "",
        f"Generated: `{status['generated_at']}`",
        "",
        f"Claim scope: {status['claim_scope']}.",
        "",
        "## Counts",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ]
    for key in ("harnesses", "lib", "integration", "ai", "proof_sources", "teeth_verified", "exceptions"):
        lines.append(f"| {key} | {counts[key]} |")
    lines.extend(["", "## Harnesses", ""])
    for item in status["harnesses"]:
        lines.append(f"- `{item['id']}` — {item['status']}; TEETH: {item['teeth_state']}.")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--json", type=Path, default=Path("STATUS.json"))
    parser.add_argument("--markdown", type=Path, default=Path("STATUS.md"))
    args = parser.parse_args()
    status = build_status(args.root.resolve())
    args.json.write_text(json.dumps(status, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    args.markdown.write_text(render_md(status), encoding="utf-8")
    c = status["counts"]
    print(
        f"status report: {c['harnesses']} harnesses; "
        f"proof sources {c['proof_sources']}/{c['harnesses']}; "
        f"TEETH {c['teeth_verified']}/{c['teeth_eligible']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
